version: "3"

services:
  api:
    build:
      context: .
      args: 
        PYTHON_VERSION: ${PYTHON_VERSION}
    command: bash -c "flask run --host=0.0.0.0 & ./bash/computation.sh ${MAX_NUMBER_OF_JOB} & python ./utils/update_status.py"    
    container_name: alligator_api
    env_file:
      - ./.env
    environment:
      FLASK_DEBUG: 1
    ports:
      - "${ALLIGATOR_PORT}:5000"
    restart: always
    volumes:
      - ./api:/code
      
  mongo:
    image: "mongo:${MONGO_VERSION}"
    container_name: "alligator_mongo"
    ports:
      - "${MONGO_PORT}:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-data:/data/db
      
  redis:
    image: redis:alpine
    container_name: alligator_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always  
    volumes:
      - './redis-data:/data'   

  jupyter:
    image: roby944/jupyter-tensorflow-extended
    container_name: alligator_jupyter
    env_file:
      - ./.env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "${JUPYTER_PORT}:8888"
    restart: always   
    volumes:
      - ./work:/home/jovyan/work
      - ./api:/home/jovyan/work/api
      - ~/my-data:/home/jovyan/work/my-data
      - ~/my-data:/data/my-data
